// Generated by manage-types script
export interface TransactionOverlayProps {
  txn: Transaction | null;
  setSelectedTxn: (txn: Transaction | null) => void;
}

export interface Transaction {
  id: string;
  date: string;
  description: string;
  amount: number;
  type: string;
  category: string;
  status: string;
  important: boolean;
  recurrence: string;
  user_id: string;
}

export interface TransactionTableProps {
  filteredTransactions: Transaction[];
  page: number;
  setPage: React.Dispatch<React.SetStateAction<number>>;
}

export interface TransactionState {
  transactions: Transaction[];
  loading: boolean;
  error: string | null;
}